version: '3.2'
services:

  ## Node api
  backend:
    build:
      context: ./
    environment:
      NODE_ENV: docker
    depends_on:
      - sql
      - memcache
    ports:
      - 3000:3000
  dashboard:
    image: synoa/docker-hystrix-dashboard:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 9090:9090
  ## Mysql container for storage
  sql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: badrootpass
      MYSQL_DATABASE: nyc
      MYSQL_USER: nyc
      MYSQL_PASSWORD: nycpwd
    ports:
      - 3306:3306

  ## Memcached container for caching
  memcache:
    image: memcached
    restart: unless-stopped
    ports:
      - 11211:11211
