apiVersion: v1
kind: ReplicationController
metadata:
  name: api-rc
  namespace: nyc-tickets-api
  labels:
    name: api-rc
spec:
  replicas: 1
  selector:
    name: api-pod
    deployment: api-initial
  template:
    metadata:
      labels:
        name: api-pod
        deployment: api-initial
        status: api-active
    spec:
      containers:
      - name: master
        image: munishregistry.azurecr.io/nyc-api:1.0.1
        imagePullPolicy: IfNotPresent
        env:
          - name: NODE_ENV
            value: production
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
